version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:15"
      timezone: "America/Bogota"
    rebase-strategy: "auto"
    open-pull-requests-limit: 20
    
